[project]
name = "ruvonvllm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pre-commit>=4.3.0",
]

[dependency-groups]
dev = [
    "ruff>=0.13.2",
]
